# Generated by Django 5.2.11 on 2026-04-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movieprueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoviePrueba',
        ),
    ]
