# Generated by Django 5.2.11 on 2026-04-23 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_delete_movieprueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecredit',
            name='character',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviecredit',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_credits', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='moviecredit',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_credits', to='movies.person'),
        ),
        migrations.DeleteModel(
            name='MovieMas',
        ),
    ]
