# Generated by Django 5.2.11 on 2026-04-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_moviecredit_character_person_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
