# Generated by Django 5.2.11 on 2026-04-24 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_moviemas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviemas',
            old_name='review',
            new_name='revierw',
        ),
    ]
